# Generated by Django 6.0.1 on 2026-01-25 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('devices', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='devices.devicetype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='locations.hospital')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripResult',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='result', serialize=False, to='trips.trip')),
                ('result_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Trip Result',
                'verbose_name_plural': 'Trip Results',
                'db_table': 'trip_results',
            },
        ),
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_statuses', to='core.status')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Status',
                'verbose_name_plural': 'Trip Statuses',
                'db_table': 'trip_statuses',
                'ordering': ['-changed_at'],
                'unique_together': {('trip', 'changed_at')},
            },
        ),
        migrations.CreateModel(
            name='TripUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip User',
                'verbose_name_plural': 'Trip Users',
                'db_table': 'trip_users',
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
