# Generated by Django 4.2.12 on 2026-01-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('request_number', models.CharField(max_length=20)),
                ('escort_name', models.CharField(max_length=255)),
                ('escort_phone', models.CharField(max_length=20)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('result_info', models.TextField(blank=True, null=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.equipmenttype')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.institution')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.region')),
            ],
        ),
    ]
