# Generated by Django 6.0.1 on 2026-01-24 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='locations.hospital'),
        ),
    ]
