# Generated by Django 6.0.1 on 2026-01-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_equipmenttype_name_alter_institution_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='core.equipmenttype', verbose_name='Equipment Type'),
        ),
    ]
