# Generated by Django 6.0.1 on 2026-01-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_equipment_name_equipment_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('initial', 'Initial'), ('in_progress', 'In Progress'), ('success', 'Success'), ('canceled', 'Canceled')], default='initial', max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
