# Generated by Django 6.0.1 on 2026-01-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_equipment_equipment_type_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='core.equipmenttype', verbose_name='Equipment Type'),
            preserve_default=False,
        ),
    ]
