# Generated by Django 6.0.1 on 2026-01-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='sale_date',
        ),
        migrations.AddField(
            model_name='institution',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='core.equipment', verbose_name='Equipments'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instances', to='core.equipmenttype', verbose_name='Equipment Type'),
        ),
    ]
