# Generated by Django 6.0.1 on 2026-01-25 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('long', models.DecimalField(decimal_places=2, max_digits=8)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitals', to='locations.region')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='locations.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Maintenance',
                'verbose_name_plural': 'Hospital Maintenances',
                'db_table': 'hospital_maintenance',
                'ordering': ['-maintenance_date'],
                'unique_together': {('hospital', 'maintenance_date')},
            },
        ),
    ]
