# Generated by Django 6.0.1 on 2026-01-13 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
